### ISSUE TITLE
Empty detailed information in connections and graphs

### ISSUE THREAD

**Issue by GrishinAV** [peermetrics/sdk-js#2]
Hello. Please help. Why detailed information in connections and graphs may not be filled (Audio eMOS rating, Media throughput,Packet loss etc.)? I see "There are not data for this graph". Also i see empty arrays in the browser console in the response. But I see the filled in information about the participants and their connection time, сonference time.

I connect like this (mediasoup-client version: 3.7.14):

    const peerMetrics = new PeerMetrics({
      apiRoot: 'http://localhost:8081/v1',
      apiKey: 'c5876c4084bf4609899f67da78c8a499',
      userId: this.participantId,
      userName: this.visibleName,
      conferenceId: this.conferenceId,
      conferenceName: `${this.roomName} (${this.conferenceStartDateTime?.toISOString()})`,
      pageEvents: {
        pageVisibility: true
      },
      debug: true,
    })

    await peerMetrics.initialize();

    peerMetrics.addSdkIntegration({
      mediasoup: {
        device: this.msDevice, 
        serverId: 'mediasoup-sfu-server', 
        serverName: 'MediaSoup SFU Server' 
      }
    })

**Comment by GrishinAV** [comment]
Sorry. I solved the problem. The problem was in the description of the parameters (which are mandatory and which are not).

**Comment by onel** [comment]
Got it. Glad it worked in the end. Closing
